image: node

before_script:
  - yarn

stages:
  - build
  - deploy

deploy:
  stage: deploy
  when: manual
  only:
    - master
  script:
    - sed -i "s/%version%/$CI_PIPELINE_IID/" public/manifest.json
    - yarn build
    - UPLOAD_TO_CHROME=true yarn deploy

build:
  stage: build
  only:
    - master
  script:
    - sed -i "s/%version%/$CI_PIPELINE_IID/" public/manifest.json
    - yarn build
    - yarn deploy
  artifacts:
    paths:
      - extension.zip